spring:
  # mysql info
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csu_food_delivery
    username: root
    password: mysql123456
  redis:
    host: localhost

  jpa:
    hibernate:
      # auto update table
      ddl-auto: update
    # debug show sql
    show-sql: true

  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest